---
title: "La dimensión del sector público"
author: "José C. Pernías"
date: '`r format(Sys.Date(), "%e de %B de %Y")`'
output: 
  html_document: 
    toc: yes
    toc_depth: 3
    toc_float: yes
    highlight: pygments
    theme: yeti
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Planteamiento

Responda a las siguientes preguntas a partir de la información
estadística contenida en las publicaciones:

- [Avance de la actuación económica y financiera de las Administraciones Públicas (2018)](https://www.igae.pap.hacienda.gob.es/sitios/igae/es-ES/Contabilidad/ContabilidadNacional/Publicaciones/Paginas/iaavanceactuacioneconomica.aspx), IGAE.
- [Informe sobre la clasificación funcional del gasto público (COFOG). Período 2015-2019](https://www.igae.pap.hacienda.gob.es/sitios/igae/es-ES/Contabilidad/ContabilidadNacional/Publicaciones/Paginas/iacogof.aspx), IGAE.
- [Government at a glance 2019](https://www.oecd-ilibrary.org/governance/government-at-a-glance_22214399), OECD.


1. ¿A cuánto asciende el gasto público en España en los últimos años?
¿Qué porcentaje con respecto al PIB representa el gasto público?  ¿Es
muy diferente esta última cifra con la media para los países de la
OECD?

2. ¿Cómo se distribuye el gasto público entre las diferentes
Administraciones Públicas?

3. Atendiendo a la clasificación funcional de los gastos, ¿qué grupos
de gasto tienen un mayor peso en España? ¿Cuáles son los grupos más
importantes para las diferentes Administraciones Públicas?

4. ¿A cuanto ascienden los ingresos de las Administraciones Públicas
en España? ¿Qué porcentaje representan con respecto al PIB? ¿Es muy
diferente esta última cifra con la media para los países de la
OECD?

5. ¿Cuál es el peso que tienen en España los impuestos directos, los
indirectos y las cotizaciones sociales?

6. ¿Qué valor toma la presión fiscal en España? ¿Es muy diferente de
los países de nuestro entorno?

7. ¿Cuál es el tamaño del déficit público en España? ¿Cómo se
distribuye este déficit en las diferentes Administraciones Públicas
que componen el Estado? ¿Es muy diferente el déficit de España del
de otros países de su entorno?

